# Generated by Django 4.2.2 on 2024-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FizzBuzzRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.IntegerField()),
                ('int2', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('str1', models.CharField(max_length=50)),
                ('str2', models.CharField(max_length=50)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
